### ISSUE TITLE
Data split annotation

### ISSUE THREAD

**Issue by joez17** [TIGER-AI-Lab/UniIR#1]
Nice work! 
I found that the data split strategy in Appendix has several "random" parts. Could you share the specific annotation files about the data splitting ways in all 10 datasets?

**Comment by lim142857** [comment]
M-BEIR dataset is now available at [M-BEIR](https://huggingface.co/datasets/TIGER-Lab/M-BEIR/tree/main/query/train) :) 
Remember to clone the M-BEIR repo directly instead of using HF API to download the dataset.
