### ISSUE TITLE
How is 'qinst' represented in the code?

### ISSUE THREAD

**Issue by zzk2021** [TIGER-AI-Lab/UniIR#16]
![image](https://github.com/TIGER-AI-Lab/UniIR/assets/73774678/02a22660-94d7-40dd-85d3-aac6104ed107)
![image](https://github.com/TIGER-AI-Lab/UniIR/assets/73774678/7cecbdb7-5a8e-40ff-baec-d950df73eff8)

**Comment by lim142857** [comment]
Hi, the 'qinst' is concated before the query. See # https://github.com/TIGER-AI-Lab/UniIR/blob/068998eac53f0da4747b0a144a5b73279fe8821d/src/data/mbeir_dataset.py#L221C9-L221C31
