### ISSUE TITLE
Results Difference

### ISSUE THREAD

**Issue by kimwongyuda** [TIGER-AI-Lab/UniIR#17]
I am interested in your nice work and evaluated HF model in "https://huggingface.co/TIGER-Lab/UniIR/tree/main/checkpoint/CLIP_SF".

However, the result is different with that of the paper.
I only changed the model and ran embedding, indexing, retrieval as it was.
What do you think about this result difference?

Thank you

![image](https://github.com/user-attachments/assets/95b32539-6041-4403-988d-b8c3f11baf9e)

**Comment by lim142857** [comment]
Hi,

Thank you for reaching out! Please see #15
