### ISSUE TITLE
Question regarding CLIP Zero-shot Evaluation Methodology in Table 6 of the paper

### ISSUE THREAD

**Issue by JUNJIE99** [TIGER-AI-Lab/UniIR#2]
Thank you for your good work!

I have a question regarding the evaluation methodology for CLIP Zero-shot as presented in Table 6 of the paper. 

It seems that this section utilizes the original CLIP model, which inherently does not support multimodal joint encoding. Specifically, in tasks such as q_t-->(c_i, c_t), how are the (c_i, c_t) pairs encoded? Are you also directly subject to score-level fusion? 

I would greatly appreciate any insights you could provide on this matter.

**Comment by edchengg** [comment]
Thanks for your interest!
This is correct. In short, we use score-level fusion (element-wise addition) for all tasks except task 6 and 8 (Section 6.2).
