### ISSUE TITLE
Checkpoints Release

### ISSUE THREAD

**Issue by DominicSlw** [TIGER-AI-Lab/UniIR#3]
Amazing work! When is the trained checkpoint going release?

**Comment by wenhuchen** [comment]
The smaller versions are already released at Huggingface. The larger version will be there soon.

**Comment by lim142857** [comment]
We just updated the checkpoints at https://huggingface.co/TIGER-Lab/UniIR. Please also check the Model Zoo section in the [ReadMe](https://github.com/TIGER-AI-Lab/UniIR).
