### ISSUE TITLE
unable to reproduce the results

### ISSUE THREAD

**Issue by Hodge931** [TIGER-AI-Lab/UniIR#4]
Hi, Thanks for the amazing work!

In producing the results from CLIP_SF-base, it seems that I don't get the same results as those in the paper:
TaskID  Task    Dataset Split   Metric  CandPool        Value   UnionPool       UnionValue
0       text -> image   visualnews_task0        test    Recall@1        visualnews_task0        0.1109  union   0.0
0       text -> image   visualnews_task0        test    Recall@5        visualnews_task0        0.2493  union   0.0
0       text -> image   visualnews_task0        test    Recall@10       visualnews_task0        0.3288  union   0.0001
0       text -> image   mscoco_task0    test    Recall@1        mscoco_task0_test       0.4138  union   0.0
0       text -> image   mscoco_task0    test    Recall@5        mscoco_task0_test       0.7016  union   0.0
0       text -> image   mscoco_task0    test    Recall@10       mscoco_task0_test       0.8058  union   0.0
0       text -> image   fashion200k_task0       test    Recall@10       fashion200k_task0       0.0791  union   0.0
0       text -> image   fashion200k_task0       test    Recall@20       fashion200k_task0       0.1123  union   0.0
0       text -> image   fashion200k_task0       test    Recall@50       fashion200k_task0       0.1815  union   0.0
1       text -> text    webqa_task1     test    Recall@1        webqa_task1     0.0049  union   0.0041
1       text -> text    webqa_task1     test    Recall@5        webqa_task1     0.0069  union   0.0053
1       text -> text    webqa_task1     test    Recall@10       webqa_task1     0.0081  union   0.0069
2       text -> image,text      edis_task2      test    Recall@1        edis_task2      0.0861  union   0.016
2       text -> image,text      edis_task2      test    Recall@5        edis_task2      0.1771  union   0.0707
2       text -> image,text      edis_task2      test    Recall@10       edis_task2      0.2197  union   0.1027
2       text -> image,text      webqa_task2     test    Recall@1        webqa_task2     0.094   union   0.0104
2       text -> image,text      webqa_task2     test    Recall@5        webqa_task2     0.2298  union   0.039
2       text -> image,text      webqa_task2     test    Recall@10       webqa_task2     0.3102  union   0.0697
3       image -> text   visualnews_task3        test    Recall@1        visualnews_task3        0.004   union   0.0
3       image -> text   visualnews_task3        test    Recall@5        visualnews_task3        0.0184  union   0.0004
3       image -> text   visualnews_task3        test    Recall@10       visualnews_task3        0.0369  union   0.0008
3       image -> text   mscoco_task3    test    Recall@1        mscoco_task3_test       0.001   union   0.0
3       image -> text   mscoco_task3    test    Recall@5        mscoco_task3_test       0.6712  union   0.0004
3       image -> text   mscoco_task3    test    Recall@10       mscoco_task3_test       0.8522  union   0.001
3       image -> text   fashion200k_task3       test    Recall@10       fashion200k_task3       0.0814  union   0.0
3       image -> text   fashion200k_task3       test    Recall@20       fashion200k_task3       0.1287  union   0.0
3       image -> text   fashion200k_task3       test    Recall@50       fashion200k_task3       0.215   union   0.0004
4       image -> image  nights_task4    test    Recall@1        nights_task4    0.066   union   0.0
4       image -> image  nights_task4    test    Recall@5        nights_task4    0.2689  union   0.0024
4       image -> image  nights_task4    test    Recall@10       nights_task4    0.4439  union   0.009
6       image,text -> text      oven_task6      test    Recall@1        oven_task6      0.0576  union   0.0047
6       image,text -> text      oven_task6      test    Recall@5        oven_task6      0.1758  union   0.0186
6       image,text -> text      oven_task6      test    Recall@10       oven_task6      0.247   union   0.0339
6       image,text -> text      infoseek_task6  test    Recall@1        infoseek_task6  0.0405  union   0.0009
6       image,text -> text      infoseek_task6  test    Recall@5        infoseek_task6  0.1377  union   0.0061
6       image,text -> text      infoseek_task6  test    Recall@10       infoseek_task6  0.2011  union   0.0138
7       image,text -> image     fashioniq_task7 test    Recall@10       fashioniq_task7 0.1564  union   0.0818
7       image,text -> image     fashioniq_task7 test    Recall@20       fashioniq_task7 0.2207  union   0.1171
7       image,text -> image     fashioniq_task7 test    Recall@50       fashioniq_task7 0.3205  union   0.1894
7       image,text -> image     cirr_task7      test    Recall@1        cirr_task7      0.0281  union   0.0185
7       image,text -> image     cirr_task7      test    Recall@5        cirr_task7      0.3475  union   0.1432
7       image,text -> image     cirr_task7      test    Recall@10       cirr_task7      0.4703  union   0.2153
8       image,text -> image,text        oven_task8      test    Recall@1        oven_task8      0.3581  union   0.1942
8       image,text -> image,text        oven_task8      test    Recall@5        oven_task8      0.5641  union   0.3501
8       image,text -> image,text        oven_task8      test    Recall@10       oven_task8      0.637   union   0.423
8       image,text -> image,text        infoseek_task8  test    Recall@1        infoseek_task8  0.165   union   0.0884
8       image,text -> image,text        infoseek_task8  test    Recall@5        infoseek_task8  0.3319  union   0.2085
8       image,text -> image,text        infoseek_task8  test    Recall@10       infoseek_task8  0.4188  union   0.2864

Could you help to identify the potential reasons? Thanks a lot!

**Comment by lim142857** [comment]
Thank you for your interest in our work! We will soon upload the updated base checkpoints.

**Comment by lim142857** [comment]
We just retrained the checkpoints for (UniIR)CLIP-SF Large and (UniIR)BLIP-FF Large and updated them at [HF page](https://huggingface.co/TIGER-Lab/UniIR). 
Please also check the Model Zoo section in the [ReadMe](https://github.com/TIGER-AI-Lab/UniIR).
You should be able to achieve similar results to those presented in the paper, as we have verified on our end.
