### ISSUE TITLE
Why is the total number of queries in  "M-BEIR/query/train" different from the count of queries in "mbeir_union_up_train.jsonl"?

### ISSUE THREAD

**Issue by LeeSureman** [TIGER-AI-Lab/UniIR#6]
The total numbr of queries in "M-BEIR/query/train" and "mbeir_union_up_train.jsonl" are 1150203 and 1332790, respectively. What is the reason for this discrepancy?

**Comment by lim142857** [comment]
Thank you for your interest in our work! 
In summary, `mbeir_union_up_train.jsonl` is an **up**-sampled version of the queries in M-BEIR/query/train
`mbeir_union_up_train.jsonl`: This file is the default training data for in-batch contrastive training specifically designed for UniIR models. It aggregates all the data from the train directory and **datasets with relatively smaller sizes have been upsampled to balance the training process.**
