### ISSUE TITLE
About the number of hard negative candidates

### ISSUE THREAD

**Issue by LeeSureman** [TIGER-AI-Lab/UniIR#7]
I want to know whether your models are trained with hard negatives.
In the paper's data sections (section 3.2 and 6.3), it seems that the M-BEIR query may have hard negative candidates.
But in the code's training config (like src/models/uniir_clip/clip_scorefusion/configs_scripts/large/train/inbatch/inbatch.yaml), the number hard negatives is set to 0. 
So, I want to know whether your models in Table 2 are trained with hard negatives.

**Comment by lim142857** [comment]
By default, the UniIR models(the experiment results we show In the paper) are not trained with hard-negatives.
